### ISSUE TITLE
About Knot Data Synchronization

### ISSUE THREAD

**Issue by ic005k** [ic005k/Knot#10]
Knot stores data in a directory called "KnotData", so you can synchronize this directory.

**Comment by xp12047** [comment]
😁

**Comment by xp12047** [comment]
虽然说最终解决了同步问题但是用户却多下载了工具。

**Comment by xp12047** [comment]
syncthing似乎没有安卓版。是knot安卓本身就是syncthing客户端呢？  
ipfs不知道比这个同步工具？

**Comment by xp12047** [comment]
也难为你一个人了。回头你去推广推广把。我试着分享过没效果。用的人多了功能完善的也快。你自己一个人维护也累的。

**Comment by xp12047** [comment]
我大概的看了下syncthing入门。我还注意到syncthing没有发布安卓版。你是打算用knot手机版当作syncthing的安卓版本嘛？knot手机版和pc端syncthing同步。然后knot的pc端读取？

**Comment by ic005k** [comment]
> 我还注意到syncthing没有发布安卓版

Android版本在此：https://github.com/syncthing/syncthing-android/releases/tag/1.22.2

**Comment by ic005k** [comment]
> 你是打算用knot手机版当作syncthing的安卓版本嘛？knot手机版和pc端syncthing同步。然后knot的pc端读取？

不、不，Knot只是和它们驳接而已，两边数据的同步交给更专业的Syincthing
所谓的驳接，就是感知数据变动进行自我自动刷新的功能

**Comment by ic005k** [comment]
> 也难为你一个人了。回头你去推广推广把。我试着分享过没效果。用的人多了功能完善的也快。你自己一个人开发维护也累的。

没事的，因为日常需要Todo和网络笔记等，之前用了很多类似的产品，感觉都不满意，所以才打算自己写一个，因为自己要用，会一直更新的

**Comment by ic005k** [comment]
> 我大概的看了下syncthing入门。

这个使用简单，有任何疑问可随时留言
它的主页介绍里面有关于其它GUI平台的链接：https://docs.syncthing.net/users/contrib.html#gui-wrappers

**Comment by ic005k** [comment]
@xp12047 一定注意要多多备份数据，以免调试过程中出现数据丢失

**Comment by xp12047** [comment]
> @xp12047 之前手机里装一堆软件，比如随手记、印象笔记、多看阅读、计步器等等，现在一个Knot全部搞定，更新会一直进行的，无关其他因素 当然也非常欢迎多提意见

好

**Comment by xp12047** [comment]
> @xp12047 一定注意要多多备份数据，以免调试过程中出现数据丢失

明白

**Comment by xp12047** [comment]
> > 你是打算用knot手机版当作syncthing的安卓版本嘛？knot手机版和pc端syncthing同步。然后knot的pc端读取？
> 
> 不、不，Knot只是和它们驳接而已，两边数据的同步交给更专业的Syncthing 所谓的驳接，就是感知数据变动进行自我自动刷新的功能

明白，

**Comment by xp12047** [comment]
我想说的是。这岂不是让手机更耗电了。又多装了一个app😐

**Comment by xp12047** [comment]
> > 这岂不是让手机更耗电了
> 
> 经过实测，一点都不耗电，这个里面是有一些科学的策略存在的。 如果Knot自身做这些东西的话，也同样会采取类似的策略，比如以服务的形式常驻后台等等 但耗电量几乎可以忽略不计，就像Knot常驻后台一样的省电

哦。晚点回家试试。手机端那个同步工具也配置好了。

**Comment by ic005k** [comment]
@xp12047 之后我相信你会非常喜欢这个同步工具，从电脑上往手机上或手机往电脑上倒东西实在是太方便了等等

**Comment by xp12047** [comment]
> @xp12047 之后我相信你会非常喜欢这个同步工具，从电脑上往手机上或手机往电脑上倒东西实在是太方便了等等

鞥，回头试试吧。但目前俺更喜欢ipfs

**Comment by ic005k** [comment]
> ipfs

这个真没接触过，有什么优点？能否同步文件呢

**Comment by xp12047** [comment]
> > ipfs
> 
> 这个真没接触过，有什么优点？能不能同步文件呢

我对它的认识也不多。备份可以，估计不好同步。[星际文件](https://docs.ipfs.tech/concepts/what-is-ipfs/)

**Comment by xp12047** [comment]
俺刚刚下载试了下。要说感受，除了有点慌。不大放心外没别的了。因为一开始没有和同步工具配置的时候。我先在pc端编辑了几个文字。后面手机端配对完成后，手机上面的内容把pc端的覆盖掉了。

**Comment by ic005k** [comment]
@xp12047 是的，同步策略是新文件覆盖旧文件（废话，呵呵），在我实际使用过程中，它比那些网盘更省事和快捷
其实我用了很长时间的印象笔记，它的刷新速度还不如Syncthing，可能跟Syncthing首先发现本地网络有关

同步问题解决之后，欢迎有时间的时候多提提建议和问题

**Comment by xp12047** [comment]
> @xp12047 是的，同步策略是新文件覆盖旧文件（废话，呵呵），在我实际使用过程中，它比那些网盘更省事和快捷 其实我用了很长时间的xx笔记等APP，它的刷新速度还不如Syncthing，可能跟Syncthing首先发现本地网络有关
> 
> 同步问题解决之后，欢迎有时间的时候多提提建议和问题

它这个不在同一个网络下，不知道可以不。

**Comment by ic005k** [comment]
> 它这个不在同一个网络下，不知道可以不。

我没记错的话，当然可以，它支持远程，用它自己的服务器进行中转存储

**Comment by xp12047** [comment]
> @xp12047 是的，同步策略是新文件覆盖旧文件（废话，呵呵），在我实际使用过程中，它比那些网盘更省事和快捷 其实我用了很长时间的xx笔记等APP，它的刷新速度还不如Syncthing，可能跟Syncthing首先发现本地网络有关
> 
> 同步问题解决之后，欢迎有时间的时候多提提建议和问题

俺以前用微信收藏或者，qq邮箱记事本。下过印象，但自从上了github外面那些非开源的基本不用了。

**Comment by xp12047** [comment]
> > 它这个不在同一个网络下，不知道可以不。
> 
> 我没记错的话，当然可以，它支持远程，用它自己的服务器进行中转存储
> 
> 你可以用手机流量测试下看看

我租的房子没宽带。电脑用的是手机热点。公司里的我用不了了。今天刚离职了。有空你给测试下吧

**Comment by ic005k** [comment]
> 俺以前用微信收藏或者，qq邮箱记事本。下过印象，但自从上了github外面那些非开源的基本不用了。

其实那些软件也挺好的，但是用着用着就变味了，出现了各种限制。

**Comment by xp12047** [comment]
> > 俺以前用微信收藏或者，qq邮箱记事本。下过印象，但自从上了github外面那些非开源的基本不用了。
> 
> 其实那些软件也挺好的，但是用着用着就变味了，出现了各种限制。

是的。

**Comment by ic005k** [comment]
> 有空你给测试下吧

我刚才测试了一下，完全没问题。

当你关闭手机wifi时，它会询问你是否变更设置，你点变更设置，之后打开设置界面里的数据流量就可以了，片刻，手机就又找到你的电脑了，手机端的Knot todo改个东西，马上桌面端的Knot就有了

**Comment by xp12047** [comment]
刚发现个同步问题。在手机端和pc端都有改动的情况下。如果没有启动同步工具，那么其中一方就会覆盖掉另外一方的数据。导致数据丢失。比如，我昨天在手机端记录了东西。今天刚好下载最新版，顺便在电脑上也记录了东西。然后我想同步一下吧。结果它把我手机端的丢掉了，也不好说是覆盖。我寻思着可能是我设置的同步中新文件优先导致的，然后设置了旧文件优先，同样也不行。除非同步开启。两方数据正常交叉。所以我觉得，当时提同步这个建议可能是个馊主意。方向好像偏了。

**Comment by xp12047** [comment]
当时建议数据同步是因为领导开会时，有人抱怨微信信息过多看不过来。领导说先标注未读然后...我觉得这不就是待办嘛。刚好knot这个更新速度让我感动。但是待办要是一直在手机端记显然不够方便。像他们那种天天要用电脑的。  
当把笔记也一块同步的时候我觉得也很好。问题是就上面所说，不开同步。两端都有变动的话，会造成一方数据丢掉这就会很麻烦。

**Comment by xp12047** [comment]
我觉得你是否考虑，重新回到云端备份。我能想到的是webdav，这个协议的东西我以前只用过一次。我的想法是pc端更改完webdav，手机端也是这样。但倘若其中有一端忘了webdav，是否也跟同步工具一样造成丢失。或者两端都操作后，它会有怎样的文件排序在各端下载后。

**Comment by ic005k** [comment]
@xp12047 是的，如果同步，则必须始终开着Syncthing，否则双方的文件“冲突”不太好处理，一般机器处理都是用新的覆盖旧的

关于这些问题，我也在思考，同时欢迎随时提供一些算法思路，比如网上找的有参考价值的资料等等

**Comment by xp12047** [comment]
> @xp12047是的，如果同步，则必须开始终着Syncthing，否则双方的文件“冲突”不太好处理，一般机器处理都是用新的外壳盖旧的
> 
> 关于这些问题，我也在思考，同时欢迎随时提供一些计算方法，比如网上找的有参考价值的资料等

好

**Comment by ic005k** [comment]
@xp12047 给你推荐一个  https://github.com/laurent22/joplin

**Comment by xp12047** [comment]
> @xp12047给你推荐一个 https://github.com/laurent22/joplin

鞥，这个很早我就用过，它有些问题我不满意，忘了具体什么问题了。但看的出来knot同步跟它的同步类似如果我没记错的话。我昨天还专门去看了下它的同步原理。后面慢慢我也就知道你会啥执意用同步工具了。在用同步工具比起joplin的方式是方便了些。我最近在想，ankidroid的同步服务器它是有人花钱买的嘛？即时不花钱也能用。我不太懂它是咋操作的。

**Comment by xp12047** [comment]
我的意思是，ankidroid用户很多。但用户都可以和网页端同步数据，只需要登录它的网站。它服务器的钱？   
关于那个同步工具我觉得也还行就是麻烦。首先在没有配对的情况下只能在一端修改数据然后另一端同步。或者配对完成后两边都可以更改同步。还要再去单独下载同步工具。

**Comment by xp12047** [comment]
那个joplin我没记错的话它虽然没用那个同步工具，是备份到云端，然后放到它的文件夹。但它提到那个同步工具好像。

**Comment by xp12047** [comment]
请求把win客户端体积缩小，同步问题也优化不少了。那么体积的问题给解决下吧。

**Comment by ic005k** [comment]
> 请求把win客户端体积缩小，同步问题也优化不少了。那么体积的问题给解决下吧。

好，后面会继续优化和完善的，不过你看看joplin的客户端体积，立马释然了

**Comment by xp12047** [comment]
> > 请求把win客户端体积缩小，同步问题也优化不少了。那么体积的问题给解决下吧。
> 
> 好，后面会继续优化和完善的，不过你看看joplin的客户端体积，立马释然了

所以我没用它。

**Comment by xp12047** [comment]
我发现我搞错了。无论有没有配对。都只能改动一边，另一边同步。并非在同步工具配对的情况下。两边都改动它会同步，它只能同步一方改动的。哎。

**Comment by ic005k** [comment]
> 我发现我搞错了。无论有没有配对。都只能改动一边，另一边同步。并非在同步工具配对的情况下。两边都改动它会同步，它只能同步一方改动的。哎。

joplin？

**Comment by xp12047** [comment]
> > 我发现我搞错了。无论有没有配对。都只能改动一边，另一边同步。并非在同步工具配对的情况下。两边都改动它会同步，它只能同步一方改动的。哎。
> 
> joplin？没太明白你的意思，Syncthing不存在这个现象
> 
> 可能还有其它的类似Syncthing的同步工具，空闲的时候都可以找一找，看看哪个最理想

是knot。一开始记得我试过，只要syncthing的pc端和手机端链接好。两端都改就可以进行同步。但这是有个前提，修改后的无论那一端得先同步。syncthing算是最好的了我都看了至少在开源这上面。我还得再说一遍。有一方数据变动就得同步。如果忘了又改了另一方的数据再进行同步，那么有一方的数据就没了。而且我发现个安卓版和pc版syncthing同步的时候，安卓得打开，安卓挂后台都不好用的。不然它也同步不上。

**Comment by xp12047** [comment]
建议后面有时间让knot支持webdav协议吧。

**Comment by ic005k** [comment]
> 有一方数据变动就得同步。如果忘了又改了另一方的数据再进行同步，那么有一方的数据就没了

所以这就是Syncthing存在的价值了，它总是在最短的时间内解决同一个的文件的内容冲突。

**Comment by ic005k** [comment]
> 而且我发现个安卓版和pc版syncthing同步的时候，安卓得打开

这是肯定的，否则安卓如何和桌面端的Syncthing通信呢？

**Comment by ic005k** [comment]
> 安卓挂后台都不好用的

你的手机需要设置一下，不同的手机，设置方法不同。
比如我的华为手机，需要在“应用启动管理”里面将Syncthing设置为“手动”并开启自启动等三个选项，否则息屏后过段时间，安卓系统会自动杀掉这个后台，这样的话实时同步就无从谈起了，因为安卓端的Syncthing已经停止运行了。

**Comment by ic005k** [comment]
> 建议后面有时间让knot支持webdav协议吧

好的，Knot将会不断发展的

**Comment by ic005k** [comment]
@xp12047 桌面端将Syncthing设置为开机启动，手机端设置系统别杀掉Syncthing这个后台，这样才能保证数据的实时同步和更新。

**Comment by xp12047** [comment]
> > 安卓挂后台都不好用的
> 
> 你的手机需要设置一下，不同的手机，设置方法可能不同。 比如我的华为手机，需要在“应用启动管理”里面将Syncthing设置为“手动”并开启自启动等三个选项，否则息屏后过段时间，安卓系统会自动杀掉这个后台，这样的话实时同步就无从谈起了，因为安卓端的Syncthing已经停止运行了。
> 
> 我记得OPPO手机是“电池优化”，其它品牌就不太知道了，总之就是设置安卓系统别杀掉某个后台APP即可。

我的也是华为的，mate20，该设置的都已经设置了。也没有杀死后台。同步的时候要打开那个同步应用，即时没有关掉它的后台也不行。要在syncthing的界面上才能同步。比如我打开后让它留在后台切到了knot做笔记。那么我同步的时候得切回到syncthing上，不然不能同步。

**Comment by xp12047** [comment]
> > > 安卓挂后台都不好用的
> > 
> > 
> > 你的手机需要设置一下，不同的手机，设置方法可能不同。 比如我的华为手机，需要在“应用启动管理”里面将Syncthing设置为“手动”并开启自启动等三个选项，否则息屏后过段时间，安卓系统会自动杀掉这个后台，这样的话实时同步就无从谈起了，因为安卓端的Syncthing已经停止运行了。
> > 我记得OPPO手机是“电池优化”，其它品牌就不太知道了，总之就是设置安卓系统别杀掉某个后台APP即可。
> 
> 我的也是华为的，mate20，该设置的都已经设置了。也没有杀死后台。同步的时候要打开那个同步应用，即时没有关掉它的后台也不行。要在syncthing的界面上才能同步。比如我打开后让它留在后台切到了knot做笔记。那么我同步的时候得切回到syncthing上，不然不能同步。

我在设置设置看看把。我刚仔细看到你把自动改为手动了。我试试，这个我之前没这样设置过。谢谢😊

**Comment by xp12047** [comment]
可以了，原来是我没设置好。我说咋用起来怪怪的。完全没有你说的那么好用。结果是要改成手动。。谢谢😊      
这个问题你要不要先关闭，有点长了吧。

**Comment by ic005k** [comment]
> 结果是要改成手动

对于Knot，你也可以同样改下，这样Knot就可以常驻后台，运行效果高，不用每次都打开它重头加载，Knot是没有任何后台活动的，更不用担心耗电问题。

**Comment by xp12047** [comment]
> > 结果是要改成手动
> 
> 对于结，你也可以同样改下，这样的结就可以常驻后台，运行效率高，不用每次都打开它重载，结是没有任何后台不动的，更。

哦。pc端的页面给改下吧，太丑了。

**Comment by ic005k** [comment]
> pc端的页面给改下吧，太丑了

目前的PC端，是完全基于移动端改装的，这样时间成本最小、最省事。
关键是我不会美工，连个图标都不会画，都是网上找现成的，如果有美工能参与到这个项目就非常Ok了。
你可以画一个界面或者设计一个界面，我有空的时候，看看能否实现它。
总之，Knot会不断完善和发展的。

**Comment by xp12047** [comment]
> > pc端的页面给改下吧，太丑了
> 
> 目前的PC端，是完全基于移动端改装的，这样时间成本最小、最省事。 关键是我不会美工，连个图标都不会画，都是网上找现成的，如果有美工能参与到这个项目就非常Ok了。 你可以画一个界面或者设计一个界面，我有空的时候，看看能否实现它。 总之，Knot会不断完善和发展的。

额...我也不会美工
