### ISSUE TITLE
关于同步问题反馈

### ISSUE THREAD

**Issue by xp12047** [ic005k/Knot#11]
笔记列表同步似乎有点问题。   
首先，我在电脑上新建了一个笔记本。电脑上的列表里面有。但是同步后，手机端始终没有。我改了个名，不知道咋弄的，电脑上的笔记内容也没了。

**Comment by ic005k** [comment]
之前，我可能没跟你提及Knot的自动保存机制。
无论待办还是笔记，均在关闭之后会自动保存，你检查一下操作过程，是否都关闭了它们，否则数据没有修改（保存），也就不会同步到其它设备了。

这个自动保存机制主要是为安卓考虑的，如果采用实时保存的话，势必会增加手机的电量消耗。

特别提醒：对于笔记，打开的时候会有一次保存当前笔记位置的过程，无论你是否修改了笔记。

对于你那边出现的这个现象，可能是没有保存造成的，欢迎随时提供反馈信息。

**Comment by ic005k** [comment]
另外，无论手机端还是桌面端，如果待办或笔记处于打开状态（待编辑模式），此时如果有同步数据过来，处于打开模式的待办或笔记是没有任何反应的（Knot不硬性刷新你当前正在查看或编辑的内容）。

所以，无论手机还是桌面端，当你查看或编辑完成之后，请随时关闭它们（桌面端的快捷键是ESC，手动端是返回键）。

**Comment by xp12047** [comment]
> #### 另外，无论手机端还是桌面端，如果待办或笔记处于打开状态（待编辑模式），此时如果有同步数据过来，处于打开模式的待办或笔记是没有任何反应的（Knot不硬性刷新你当前正在查看或编辑的内容，更不会强制退出当前的待办或笔记界面）。
> #### 所以，无论手机还是桌面端，当你查看或编辑完成之后，请随时关闭它们（桌面端的快捷键是ESC，手机端是返回键）。

好，明白了。现在好了。

**Comment by xp12047** [comment]
谢谢😊

**Comment by ic005k** [comment]
没事，有任何问题或建议可随时留言
