### ISSUE TITLE
关于knot笔记中引用的不解

### ISSUE THREAD

**Issue by xp12047** [ic005k/Knot#12]
就是在反馈同步问题那个时候。我在我的那个笔记里搞了个引用像这样   
>  引用        

但是显示效果看起来没啥变化好像换挡了。    
我拿另外两个app举例最后放knot的   
首先markor
![Screenshot_20221219_221508_net gsantner markor](https://user-images.githubusercontent.com/56335408/208446270-f0e9afba-729b-4c3e-8650-61808554195a.jpg)    
然后joplin      
![Screenshot_20221219_221305_net cozic joplin](https://user-images.githubusercontent.com/56335408/208446644-2cee2d04-726a-4aca-a414-a3d8f9b99eff.jpg)
最后kont
![Screenshot_20221219_221324_com x](https://user-images.githubusercontent.com/56335408/208446537-2947158a-e29a-4a69-ac58-5495ac2c41f4.jpg)      
关于这个情况后面能不能给优化下。   
另外有支持将笔记导出为pdf文件的计划嘛？

**Comment by ic005k** [comment]
这是一个已知的风格问题，另外一个就是分隔符“---”，Knot会显示为空格行，而不是一条横线。
这两个风格上的小细节，后面再研究解决。
至于输出pdf，先记下来，后面再考虑如何实现。
目前的当务之急是完善基础框架，消除一切bug，有任何想法，可随时留言。
至于app界面问题，你也可以推荐一些非常优秀的app界面参考下

总之，Knot会不断发展，这是肯定不会改变的

**Comment by xp12047** [comment]
> 这是一个已经知道的pdf风格问题，另外一个就是分隔符“---”，Knot会显示为空格行，而不是一条横线。 这两个风格于细节上的细节，后裙露出再 凿。 ，先下来，后面再如何实现 目前的当务之急当务之急框架框架框架框架框架，bug，bug，有有，可任何想法， app界面
> 
> 总之，结不会断展开，这是肯定不会改变的

哦

**Comment by xp12047** [comment]
我还想问个问题。你为啥给它起名叫knot呢？

**Comment by ic005k** [comment]
> 为啥给它起名叫knot呢

Knot是绳结的意思，古代采用结绳记事，是一种有效的非常简单不复杂的记事方法，所以Knot的目标就是简单不复杂，但又能记录一切你想要记录的事物，大致上就是这样子，呵呵。
也就是说，Knot只能更加简单，因为把一件事情弄复杂（比如非常多的功能、花哨的界面等等）很容易，但弄得非常简单但又不失功能，实属不易，大道至简。

如果你有其他创意，也可以提出来探讨。

**Comment by ic005k** [comment]
> > 为啥给它起名叫knot呢
> 
> Knot是绳结的意思，古代采用结绳记事，是一种有效的非常简单不复杂的记事方法，所以Knot的目标就是简单不复杂，但又能记录一切你想要记录的事物，大致上就是这样子，呵呵。 也就是说，Knot只能更加简单，因为把一件事情弄复杂（比如非常多的功能、花哨的界面等等）很容易，但弄得非常简单又不失功能，实属不易，大道至简。
> 
> 如果你有其他创意，也可以提出来探讨。

**Comment by xp12047** [comment]
之前我记得有关pc界面太丑。后来我想可以参考下windows上面的记事本或者word，简单简洁也不算太丑。

**Comment by ic005k** [comment]
> 可以参考下windows上面的记事本或者word，简单简洁也不算太丑

好的，后面会考虑的
