### ISSUE TITLE
希望增加从其它地方分享的数据

### ISSUE THREAD

**Issue by xp12047** [ic005k/Knot#13]
比如我在浏览网页的时候。刚好看到需要保存到笔记的内容长按通常会有分享，然后可以分享到笔记软件里面。这个希望以后knot能有。   

https://user-images.githubusercontent.com/56335408/209475333-a7428afb-aaef-4a61-8295-33cbdc035ca9.mp4

**Comment by xp12047** [comment]
看你学分里面提到了qown，这个我之前用过。当时主要看它体积小，后来嘛放弃了。跟你分享个[笔记软件](https://github.com/nuttyartist/notes)

**Comment by ic005k** [comment]
好的，已记录。

**Comment by ic005k** [comment]
> 跟你分享个[笔记软件](https://github.com/nuttyartist/notes)

这个我似乎接触过，界面很轻爽，其实笔记类的app还是非常之多的，关键在于能否在多个终端无缝同步数据，否则单单的一个笔记app已无任何现实意义

**Comment by xp12047** [comment]
> > 跟你分享个[笔记软件](https://github.com/nuttyartist/notes)
> 
> 这个我似乎接触过，界面很轻爽，其实笔记类的app还是非常之多的，关键在于能否在多个终端无缝同步数据，否则单单的一个笔记app已无任何现实意义

是的
