### ISSUE TITLE
可以在改进下备忘录嘛？

### ISSUE THREAD

**Issue by xp12047** [ic005k/Knot#2]
备忘录markdown不支持表格嘛？其它的都很棒！

**Comment by ic005k** [comment]
支持表格的，比如你在“源”里面输入（或粘贴）下面的表格样式

|表头1 |表头2 |
|----|----|
|**单元格1**|**单元格2**|
|**单元格3**|**单元格4**|

**Comment by ic005k** [comment]
欢迎随时对各项功能提出各种改进意见，我会持续不断地更新Knot的

**Comment by xp12047** [comment]
> 支持表格，比如你在“源”里面（编辑表格最好在“源”里面）输入（或者下面的）下面的表格样式（样式需要在编辑时显示）
> 
> 表头1	表头2
> **单元格1**	**单元格2**
> **单元格3**	**单元格4**
哦，完成后是这个样子子？  
不是这种格式编写？
|a|b| 
|---|---|    
|c|d|
![Screenshot_20221001_175536_com x](https://user-images.githubusercontent.com/56335408/193403866-005ce013-acbd-4ad9-81c2-986e42cdbc80.jpg)
![Screenshot_20221001_175540_com x](https://user-images.githubusercontent.com/56335408/193403869-4501908a-7a26-41f4-bff7-252be9dce0b2.jpg)

**Comment by xp12047** [comment]
单元格和单元格之间是有个制表符？

**Comment by ic005k** [comment]
> |a|b|
> |---|---|
> |c|d|

是的，是这种格式，我用代码的方式贴一个，如下：

`|表头1 |表头2 |
|----|----|
|**单元格1**|**单元格2**|
|**单元格3**|**单元格4**|`

**Comment by ic005k** [comment]
相关内容，你可以参考下面的这个：

https://www.zybuluo.com/mdeditor#full-editor

**Comment by ic005k** [comment]
我将上面链接例子中的6和7贴到Knot备忘录的“源”里面，最终结果如下图：

![最终结果](https://user-images.githubusercontent.com/25247437/193410617-32793143-0c59-4930-a5ba-42c9bfc223c1.png)

**Comment by xp12047** [comment]
> 我将上面链接例子中的6和7贴到Knot备忘录的“源”里面，最终结果如下图：
> 
> ![最终结果](https://user-images.githubusercontent.com/25247437/193410617-32793143-0c59-4930-a5ba-42c9bfc223c1.png)

谢谢，我再试了多次以后还不太确定的发现。单元格的内容如果一个字节。它可能显示不了表格。

**Comment by ic005k** [comment]
没关系，下个版本我弄个格式化的按钮，你直接定制行和列之后，生成一个现成的表格

**Comment by xp12047** [comment]
> 没关系，下个版本我弄个格式化的按钮，你直接定制行和列之后，生成一个现成的表格
谢谢😊   
你有时间能不能给开发个打字软件。[例子](https://github.com/wongsingfo/86wubi)windows版本的离线使用，不需要它那里面的汉字编码提示，可以保存进度。不限输入法，只要汉字对的上就好。

**Comment by xp12047** [comment]
> 没关系，下个版本我弄个格式化的按钮，你直接定制行和列之后，生成一个现成的表格

俺觉得你开发的东西很棒，我搜遍了整个github也没有找到简单，好用的。那个雨天跟打器不好用。太杂不够简单。

**Comment by ic005k** [comment]
好，欢迎多提建议。新功能已增加，你试用看看，可直接生成表格（在“源”里面）。
可在APP菜单里面选择“关于”，再选择“下载（镜像）”完成升级。

**Comment by xp12047** [comment]
> 好，欢迎多提建议。新功能已增加，你试用看看，可直接生成表格（在“源”里面）。 可在APP菜单里面选择“关于”，再选择“下载（镜像）”完成升级。

谢谢

**Comment by ic005k** [comment]
> 你有时间能不能给开发个打字软件。[例子](https://github.com/wongsingfo/86wubi)windows版本的离线使用，不需要它那里面的汉字编码提示，可以保存进度。不限输入法，只要汉字对的上就好。

我先看下，例子里面好像是5笔输入？貌似5笔基本上没人用了，不过你给的这个例子，倒是可以学习下，感谢分享

**Comment by ic005k** [comment]
还有，Knot采用滚动升级的方法（为了节省时间），你可定期在“关于”界面完成下载和升级

**Comment by xp12047** [comment]
> 还有，Knot采用滚动升级的方法（为了节省时间），你可定期在“关于”界面完成下载和升级

好的，谢谢😄

**Comment by xp12047** [comment]
> > 你有时间能不能给开发个打字软件。[例子](https://github.com/wongsingfo/86wubi)windows版本的离线使用，不需要它那里面的汉字编码提示，可以保存进度。不限输入法，只要汉字对的上就好。
> 
> 我先看下，例子里面好像是5笔输入？貌似5笔基本上没人用了，不过你给的这个例子，倒是可以学习下，感谢分享

谢谢你能感兴趣。鞥，是练习五笔的。我就是通过它学习的五笔。不过。我拿它练双拼的话有点别扭，不想看到那个编码提示。我自己不会编程。我看你仓库里面开发了好几个工具都很棒。我认为打字软件不需要太过于专业。越简单越好。就是那个例子里面的把编码去掉做成本地的可以保存进度，或者加个wpm计时也行。我不知道该怎么形容，就是直接在原文字的上面打字，错的话它不会覆盖，对的话就覆盖掉。
总结:
1. 本地
2. 打字进度保存
3. 不限输入法匹配的是汉字
4. 打字覆盖原文(这个超级有用不然抄的东西多了忘了抄哪儿了)  
5. 文字统计，计时(可有可无)

**Comment by xp12047** [comment]
最后谢谢你😊我提了那么多跟这个项目无关的东西你也不生气。不过话说回来就刚才那个需求，整个github竟然找不到。期待你用c plus plus开发!

**Comment by ic005k** [comment]
好的，只要时间允许，我会考虑的
其实，最简单的办法就是你给原始作者提出你的想法，作者应该很快就能做出调整和更改，这是效率最高的办法

**Comment by xp12047** [comment]
> 好的，只要时间允许，我会考虑的 其实，最简单的办法就是你给原始作者提出你的想法，作者应该很快就能做出调整和更改，这是效率最高的办法

谢谢。他可能不会搭理我。。

**Comment by xp12047** [comment]
今天更新的版本已经下载使用，那个插入表格的功能确实省力。😄

**Comment by ic005k** [comment]
> 今天更新的版本已经下载使用，那个插入表格的功能确实省力。😄

嗯，这块几乎做了全新的设计。刚才又发了一版，解决了部分手机在编辑备忘录时，工具栏界面会超出屏幕之外的现象。

**Comment by xp12047** [comment]
> > 今天更新的版本已经下载使用，那个插入表格的功能确实省力。😄
> 
> 嗯，这块几乎做了全新的设计。刚才又发了一版，解决了部分手机在编辑备忘录时，工具栏界面会超出屏幕之外的现象。

😁👍
