### ISSUE TITLE
备忘录链接有办法点击跳转吗

### ISSUE THREAD

**Issue by xp12047** [ic005k/Knot#3]
比如[点击链接跳转](链接地址)  点击它会跳转到网页。

**Comment by ic005k** [comment]
这个功能一直有的，你可以在编辑状态下插入一个链接试试（工具栏上）？，完成后回到浏览界面就可以点击了，注意在编辑状态下是不能点击链接的。

**Comment by ic005k** [comment]
包括email地址的自动检测、图片的二次预览等功能都是有的

**Comment by ic005k** [comment]
还有一种可能是你的链接地址没有包含http，需要一个完整的链接比如 https://github.com/ic005k/Knot/issues/3
你可以用工具栏上的插入链接这个模板来修改

**Comment by ic005k** [comment]
在红色粘贴按钮的上面就是插入链接的按钮

**Comment by ic005k** [comment]
> 拿默认的knot那个点了也没反应

那就奇怪了，除非你将这个链接放在第一行（最前面）？最首行不接受超链接等特殊格式。

**Comment by ic005k** [comment]
至于最首行为啥不接受超链接的点击，这似乎是开发工具决定的事情（我一直采用其默认行为）？
不过，我回头有空的话，会认真研究分析一下的。

**Comment by ic005k** [comment]
如果还有其他的模块发现了问题，比如阅读器、待办事项等模块，可随时留言，有时间我都会跟进处理的，目的就是使这个工具软件更成熟、更简洁好用，我将不断完善它

**Comment by xp12047** [comment]
> 如果还有其他的模块发现了问题，比如阅读器、待办事项等模块，可随时留言，有时间我都会跟进处理的，目的就是使这个工具软件更成熟、更简洁好用，我将不断完善它

你咋不宣传宣传这个工具呢？v2上面或者。。很好的工具啊

**Comment by xp12047** [comment]
> > 如果还有其他的模块发现了问题，比如阅读器、待办事项等模块，可随时留言，有时间我都会跟进处理的，目的就是使这个工具软件更成熟、更简洁好用，我将不断完善它
> 
> 你咋不宣传宣传这个工具呢？v2上面或者。。很好的工具啊

我自己不怎么看小说。有的时候就是看些pdf文档。另外我觉得看小说的功能不如改成rss订阅，或者把步数那个砍掉新增rss订阅。

**Comment by xp12047** [comment]
二次编辑的时候有办法定位到最后一次编辑的位置吗？而不是首行的位置
![Screenshot_20221012_120338_com x](https://user-images.githubusercontent.com/56335408/195247682-1ba214ea-dc6e-4971-b18e-b0ed77834c5f.jpg)
![Screenshot_20221012_120346_com x](https://user-images.githubusercontent.com/56335408/195247687-e779c308-843d-47a2-929f-dbc0346b341a.jpg)

**Comment by ic005k** [comment]
> 你咋不宣传宣传这个工具呢？v2上面或者。。很好的工具啊

主要是没时间啊，平时太忙了

**Comment by xp12047** [comment]
备忘录有办法作标签或者归档处理吗？如果都记在一个页面东西多了，不好找。也不能单独导出备忘录

**Comment by xp12047** [comment]
> > 你咋不宣传宣传这个工具呢？v2上面或者。。很好的工具啊
> 
> 主要是没时间啊，平时太忙了

哦

**Comment by ic005k** [comment]
> 不怎么看小说

其实写这个阅读器的初衷并不是为了看小说，而是看epub格式的技术书籍（比如数学、计算机之类的技术书籍），它可以查看里面的图片，而且采用长页面等。

**Comment by xp12047** [comment]
> > 不怎么看小说
> 
> 其实写这个阅读器的初衷并不是为了看小说，而是看epub格式的技术书籍（比如数学、计算机之类的技术书籍），它可以查看里面的图片，而且采用长页面等。

哦

**Comment by ic005k** [comment]
> 不如改成rss订阅

rss已是很古老的技术了，在pc时代是比较流行的，但在移动互联时代，已经没多少人提起它了
目前新闻还是“头条”之类的东西在流行

**Comment by ic005k** [comment]
> 二次编辑的时候有办法定位到最后一次编辑的位置吗？

这个没问题，是个好建议，下个版本将实现它

**Comment by ic005k** [comment]
> 备忘录有办法作标签或者归档处理吗？如果都记在一个页面东西多了，不好找。也不能单独导出备忘录

没问题，这个功能会考虑的，有时间我就会不断完善它

**Comment by ic005k** [comment]
总之有任何需求或想法，请随时留言，我都会查看并分析或实施的

**Comment by xp12047** [comment]
> > 不如改成rss订阅
> 
> rss已是很古老的技术了，在pc时代是比较流行的，但在移动互联时代，已经没多少人提起它了 目前新闻还是“头条”之类的东西在流行

哦

**Comment by xp12047** [comment]
我不大好意思开问题了就接着这个帖子发吧，别介意。很佩服你解决问题的速度，刚发布的我也在用了很棒😊。但我有个小小的疑问以及有点别扭的地方还是关于那个备忘单。疑问是不支持表情吗？比如:+1: ，别扭的地方是当我记录超过一叶屏的东西，我往上翻的时候它一弹一弹的。。另外现在改进那个直接定位到最后一次编辑的位置真的超级棒😊😊👍

**Comment by ic005k** [comment]
> 不支持表情吗？

是支持的，你在编辑状态下直接通过手机的输入法输入表情即可，保存后也能正常显示。

**Comment by ic005k** [comment]
> 当我记录超过一叶屏的东西，我往上翻的时候它一弹一弹的

这个问题我这边倒是没有出现，是滚动不平滑还是什么呢，能具体一些吗？

**Comment by ic005k** [comment]
> 图片上的那个笔记也算是可以暂时保存的是吧？并没看到有保存按钮

是的，内容是自动保存的，你关闭它的时候就自动保存了。
这个功能主要是为每个标签页提供一些简单的文本备注，比如“汽车保养”标签页，可以简单备注些与之相关的内容等等

**Comment by ic005k** [comment]
Knot是采用的一种通用数学模型，用来记录任何身边发生的事情

**Comment by ic005k** [comment]
> 我不大好意思开问题了

这个没关系的，一个好的app需要用户不断提出各种改进方案才能趋于完善，随时欢迎提问题

**Comment by xp12047** [comment]
> > 当我记录超过一叶屏的东西，我往上翻的时候它一弹一弹的
> 
> 这个问题我这边倒是没有出现，是滚动不平滑还是什么呢，能具体一些吗？


https://user-images.githubusercontent.com/56335408/196014408-bbfa7ef5-da91-4489-98eb-31177d524fbc.mp4
可能是我的手机问题吧。

**Comment by xp12047** [comment]
> > 图片上的那个笔记也算是可以暂时保存的是吧？并没看到有保存按钮
> 
> 是的，内容是自动保存的，你关闭它的时候就自动保存了。 这个功能主要是为每个标签页提供一些简单的文本备注，比如“汽车保养”标签页，可以简单备注些与之相关的内容等等

哦，谢谢😊

**Comment by xp12047** [comment]
> > 我不大好意思开问题了
> 
> 这个没关系的，一个好的app需要用户不断提出各种改进方案才能趋于完善，随时欢迎提问题

刚才点错了打开了。鞥，你开发效率真的没得说很快。

**Comment by xp12047** [comment]
![Screenshot_20221016_103206_com x](https://user-images.githubusercontent.com/56335408/196015118-903d027e-c2d5-48d7-acca-7b7f0f0724e5.jpg)
我之前并没有好好使用过这个记账的功能。如果要删除单条消费记录，是点那个减号嘛？上面显示是减少一次？这个减少在导出数据后还有吗？

**Comment by ic005k** [comment]
> 可能是我的手机问题吧

这应该不是手机的问题，内容的上下翻滚是有加速效果的，如果你快速向上或向下滑动，则自动启用了加速，你稍微慢点滑动看看

**Comment by ic005k** [comment]
> 我之前并没有好好使用过这个记账的功能。如果要删除单条消费记录，是点那个减号嘛？上面显示是减少一次？这个减少在导出数据后还有吗？

减号只是删除当天的最后一条记录，这个操作是实时的，导出数据只是针对当前存在的所有数据

**Comment by ic005k** [comment]
> 这个减少在导出数据后还有吗？

肯定没有了，因为你已经删除这条记录了，导出的数据里面肯定就不包含被删除的内容了

**Comment by xp12047** [comment]
> > 我之前并没有好好使用过这个记账的功能。如果要删除单条消费记录，是点那个减号嘛？上面显示是减少一次？这个减少在导出数据后还有吗？
> 
> 减号只是删除当天的最后一条记录，这个操作是实时的，导出数据只是针对当前存在的所有数据

那我要是想删除当天其中的一条记录该怎么操作？

**Comment by ic005k** [comment]
> 那我要是想删除当天其中的一条记录该怎么操作？

目前不提供这个操作机制，只允许删除当天最后一条记录，其它的记录可以双击条目进行修改
这个机制是为了防止作弊或误操作而导致数据丢失
后面的版本会不会更改这个删除机制，暂时不好说，要综合各个不同的用户群体

**Comment by ic005k** [comment]
有任何想法或疑问，欢迎随时针对某个问题开新话题进行讨论，话题太长，不便于浏览和回复

**Comment by ic005k** [comment]
还有，如果你是设计者，你会如何设计它，这些等等，都欢迎探讨

**Comment by xp12047** [comment]
> > 那我要是想删除当天其中的一条记录该怎么操作？
> 
> 目前不提供这个操作机制，只允许删除当天最后一条记录，其它的记录可以双击条目进行修改 这个机制是为了防止作弊或误操作而导致数据丢失 后面的版本会不会更改这个删除机制，暂时不好说，要综合各个不同的用户群体

哦

**Comment by xp12047** [comment]
> 还有，如果你是设计者，你会如何设计它，这些等等，都欢迎探讨

我还是觉得应该在阅读器上面增加rss订阅功能。或者可以订阅网页更新的。这个你自己考虑吧，俺觉得rss很实用。谢谢😊

**Comment by ic005k** [comment]
> 在阅读器上面增加rss订阅功能

好，这个需求我先记下来

**Comment by xp12047** [comment]
> > 在阅读器上面增加rss订阅功能
> 
> 好，这个需求我先记下来

谢谢😊
