### ISSUE TITLE
建议阅读器增加支持pdf的功能

### ISSUE THREAD

**Issue by xp12047** [ic005k/Knot#4]
强烈建议阅读器增加对pdf文件的支持。
![Screenshot_20221113_080102_com x](https://user-images.githubusercontent.com/56335408/201499417-390bdf91-e290-4742-bca4-435ef7f13e46.jpg)
另外我刚升级的版本咋和你截图的不一样，看最上方。

**Comment by ic005k** [comment]
> 强烈建议阅读器增加对pdf文件的支持。

好的，我先记下来，有空闲时间我就会考虑如何实施它。最近尽在修复问题，没增加什么新功能。

**Comment by ic005k** [comment]
> 我刚升级的版本咋和你截图的不一样，看最上方

这个截图是模拟器上的，多了一个蓝色的“运行”按钮，该功能是开启和关闭加速度传感器用的，为了给那些没有内置计步器芯片的手机用的。
现在的新式手机都内置了计步传感器，不需要利用加速度传感器来计算步数，所以自动隐藏了这个按钮。

**Comment by xp12047** [comment]
> > 我刚升级的版本咋和你截图的不一样，看最上方
> 
> 这个截图是模拟器上的，多了一个蓝色的“运行”按钮，该功能是开启和关闭加速度传感器用的，为了给那些没有内置计步器芯片的手机用的。 现在的新式手机都内置了计步传感器，不需要利用加速度传感器来计算步数，所以自动隐藏了这个按钮。

哦，谢谢😊
