### ISSUE TITLE
关于记账图片导出

### ISSUE THREAD

**Issue by xp12047** [ic005k/Knot#6]
记账导出图像不错。但是每一条的祥细内容没有。记账时候的"详细"内容能不能也一并导出到图像上面。

**Comment by ic005k** [comment]
好的，我会考虑的，已记下。
之前我也有考虑到这个细节，但一直没太多时间来完善，感谢反馈，欢迎发现跟多的问题。

**Comment by xp12047** [comment]
> 好的，我会考虑的，已记下。 之前我也有考虑到这个细节，但一直没太多时间来完善，感谢反馈，欢迎发现跟多的问题。

谢谢😊
