### ISSUE TITLE
关于待办的疑问

### ISSUE THREAD

**Issue by xp12047** [ic005k/Knot#8]
有没有考虑过出个pc端的cli程序用来同步手机端待办？  
我是想既然有了这个功能可否让它更专业些。  
最关键的我想就是同步待办。有时候记待办翻待办总在手机不方便。  
但是knot其它功能的数据我觉得没必要同步，也就是待办。  
[cli待办同步待办](https://github.com/sachaos/todoist)   
如果我没记错，它待办优先级a-z，而且可以选择颜色标注。

**Comment by ic005k** [comment]
可以考虑，欢迎提供各种技术方案

**Comment by ic005k** [comment]
如果采用客户端的话，是不是太繁琐了，需要在各个平台下载安装
网页端是最好的，无需下载安装客户端，你那边也可以研究下

**Comment by xp12047** [comment]
> 如果采用客户端的话，是不是太繁琐了，需要在各个平台下载安装 网页端是最好的，无需下载安装客户端，你那边也可以研究下

是，网页端也很好。关键只要能和手机端同步下。另外最好有颜色标注。

**Comment by ic005k** [comment]
没事，你只需搜集和提供相关技术线索就行，至于如何实施，我来进行

**Comment by xp12047** [comment]
> 没有事，你只需要搜集和提供相关技术线路探索就进行，至于如何实施，我来进行

好，谢谢

**Comment by xp12047** [comment]
## 搜索 todo web 搜出来的一些东西

[Tracks 是一个 GTD™ 网络应用程序，使用 Ruby on Rails 构建](https://github.com/TracksApp/tracks)  
[仅键盘任务管理网络应用程序](https://github.com/huytd/pomoday-v2)   
[GAE + Backbone + Require.js Todo 网络应用程序示例](https://github.com/ronreiter/todo-app)  
[使用各种 Web 组件技术构建的简单待办事项列表](https://github.com/shprink/web-components-todo)  
[使用 Laravel 和 Vue.js 构建的 Todolist Web 应用程序的前端应用程序](https://github.com/guillaumebriday/todolist-frontend-vuejs)  
[与 todo.txt 文件一起使用的 Web UI](https://github.com/bicarbon8/todoTxtWebUi)

**Comment by ic005k** [comment]
现在主要问题是解决跨设备数据同步，欢迎任何想法

**Comment by ic005k** [comment]
移动端更要兼顾电量的消耗，要有数据修改才触发，比如不能每隔30分钟或1小时等时间间隔就同步一次，这显然是不科学的

**Comment by xp12047** [comment]
> 现在主要问题是解决跨设备数据同步，欢迎任何想法 当然，手动同步问题不大，主要是全自动同步，比如移动端数据修改，桌面端自动同步，反之亦然

我觉得手动同步完全可以了。自动没必要吧。只要保证同步时的数据准确就行。

**Comment by xp12047** [comment]
> 移动端更要兼顾电量的消耗，要有数据修改才触发，比如不能每隔30分钟或1小时等时间间隔就同步一次，这显然是不科学的
> 
> 不知你有什么好的、简单的、可靠的、有效的思路

是。我觉得暂时别搞自动同步了把。弄个下拉刷新或者手动够用。

**Comment by ic005k** [comment]
好的，我先完善各个平台的客户端

**Comment by xp12047** [comment]
> 好的，我先完善各个平台的客户端

谢谢😊

**Comment by xp12047** [comment]
> 在新版中发布了各个平台的APP，欢迎测试和发现问题 APP完成后，接下来的重点就是各平台数据同步问题了

好好😁

**Comment by xp12047** [comment]
> > 在新版中发布了各个平台的APP，欢迎测试和发现问题APP完成后，接下来的重点就是各平台数据同步问题了
> 
> 好😁

pc端windows版刚下载试用了下。坦白的讲界面跟用安卓模拟器差不多。所以我觉得要不你还是弄个web版吧。界面也不好看，内存占有200多m。  
像你一开始计划的web版就很好了。

**Comment by xp12047** [comment]
只要同步待办就好了。你说你pc端咋还有阅读器和步数啥的啊。假如安装公司电脑上，领导看到这个软件他会咋想。他应该认为我在看小说吧。

**Comment by ic005k** [comment]
> 所以我觉得要不你还是弄个web版吧

这个可能实现不了，因为需要独立的服务器支持，花钱买服务器肯定是不现实的，而且不长久，所以目前不太好处理，但安卓端会不断优化和完善的，目前至于其它客户端，先让其存在，再看看如何改善和处理
所以各设备端数据同步需要另辟蹊径了

有任何建议，可随时提供

**Comment by ic005k** [comment]
> 只要同步待办就好了。你说你pc端咋还有阅读器和步数啥的啊。假如安装公司电脑上，领导看到这个软件他会咋想。他应该认为我在看小说吧。

这只是第一个版本，最初步的，只是一个原型而已，后面如果可行的话，肯定是会重新设计的

**Comment by xp12047** [comment]
> > 所以我觉得要不你还是弄个web版吧
> 
> 这个可能实现不了，因为需要独立的服务器支持，花钱买服务器肯定是不现实的，而且不长久，所以目前不太好处理，但安卓端会不断优化和完善的，目前至于其它客户端，先让其存在，再看看如何改善和处理 所以各设备端数据同步需要另辟蹊径了
> 
> 有任何建议，可随时提供

哦。那建议只保留待办那个吧，做成windows便签那种。  小巧实用。

**Comment by ic005k** [comment]
还有，如果解决不了各设备之间的数据同步，其它客户端就没有存在的必要了，所以客户端随时都可以去掉，这个倒不用担心

**Comment by xp12047** [comment]
> 还有，如果解决不了各设备之间的数据同步，其它客户端就没有存在的必要了，所以客户端随时都可以去掉，这个倒不用担心

哦，

**Comment by ic005k** [comment]
> 那建议只保留待办那个吧，做成windows便签那种。 小巧实用

这都是小事情，随时都可以更改和重新设计，只是先要搞定数据同步，其它才有存在的意义。

**Comment by xp12047** [comment]
> > 那建议只保留待办那个吧，做成windows便签那种。 小巧实用
> 
> 这都是小事情，随时都可以更改和重新设计，只是先要搞定数据同步，其它才有存在的意义。

明白。

**Comment by ic005k** [comment]
目前Knot只具有备份和恢复数据的功能，通过在手机上在线备份，在桌面端可以下载这个数据，反之亦然
虽然可以共享和查看数据，但太不智能了，而且数据容易造成互相覆盖

**Comment by ic005k** [comment]
可能会卡在数据同步这个地方很长时间，但我觉着一定会有一种算法可以解决这个问题

**Comment by xp12047** [comment]
> 目前Knot只具有备份和恢复数据的功能，通过在手机上在线备份，在桌面端可以下载这个数据，反之亦然 虽然可以共享和查看数据，但太不智能了，而且数据容易造成互相覆盖

明白。但我是真觉得。除了待办，其它的数据可以导出就行。

**Comment by ic005k** [comment]
> 除了待办，其它的数据可以导出就行

这都不是事，如果解决了数据同步的话。待办只是其中的一种数据而已

**Comment by xp12047** [comment]
> 目前Knot只具有备份和恢复数据的功能，通过在手机上在线备份，在桌面端可以下载这个数据，反之亦然 虽然可以共享和查看数据，但太不智能了，而且数据容易造成互相覆盖

[todo.txt](https://github.com/todotxt/todo.txt)如果只同步手机端的待办。待办同步的时候又是这种格式情况不知道会好些嘛？当然我目前还没导出待办看它的格式是什么样的。

**Comment by xp12047** [comment]
> > 除了待办，其它的数据可以导出就行
> 
> 这都不是事，如果解决了数据同步的话。待办只是其中的一种数据而已

要实现自动同步的话似乎都得需要服务器吧。不然就是你说的特定格式云端备份，电脑下载。多设备，不需要花钱买服务器好像就是在同一wifi下可以？

**Comment by ic005k** [comment]
todo.txt好像也只能在本地使用，能跨客户端互通吗？没用过这个工具
不过，Knot可以做到和任何其它开放性的todo互通，这是没问题的

**Comment by ic005k** [comment]
> 要实现自动同步的话似乎都得需要服务器吧。不然就是你说的特定格式云端备份，电脑下载。多设备，不需要花钱买服务器好像就是在同一wifi下可以？

所以这是一个挑战，希望我们能解决它

**Comment by xp12047** [comment]
> > 要实现自动同步的话似乎都得需要服务器吧。不然就是你说的特定格式云端备份，电脑下载。多设备，不需要花钱买服务器好像就是在同一wifi下可以？
> 
> 所以这是一个挑战，希望我们能解决它

todo.txt那个我也没用过。我是想着。knot本身我看也开放api。通过api读取它的todo.txt格式。支持todo.txt格式的工具也有些。

**Comment by xp12047** [comment]
> > 要实现自动同步的话似乎都得需要服务器吧。不然就是你说的特定格式云端备份，电脑下载。多设备，不需要花钱买服务器好像就是在同一wifi下可以？
> 
> 所以这是一个挑战，希望我们能解决它

似乎只能同一wifi能实现自动同步。我这些了解的都不多帮不上啥忙。回头你弄个二维码我请你喝杯咖啡吧。

**Comment by ic005k** [comment]
> 通过api读取它的todo.txt格式

这是没问题的，如果需要的话。

**Comment by ic005k** [comment]
> 似乎只能同一wifi能实现自动同步。我这些了解的都不多帮不上啥忙。回头你弄个二维码我请你喝杯咖啡吧。

wifi同域，其实就是一个局域网，不能远程
谢了，咖啡就不喝了，欢迎提供各种技术线索，哪怕看起来是异想天开，相信也能带来启发

**Comment by xp12047** [comment]
> > 通过api读取它的todo.txt格式
> 
> 这是没问题的，如果需要的话。

好，这个问题我先关了吧。回头再另开吧

**Comment by xp12047** [comment]
> > 似乎只能同一wifi能实现自动同步。我这些了解的都不多帮不上啥忙。回头你弄个二维码我请你喝杯咖啡吧。
> 
> wifi同域，其实就是一个局域网，不能远程 谢了，咖啡就不喝了，欢迎提供各种技术线索，哪怕看起来是异想天开，相信也能带来启发

不能远程也没关系。有些好点的公司里面它倒是给给wifi用。比电脑云端下载数据在打开方便了。

**Comment by ic005k** [comment]
> 不能远程也没关系。有些好点的公司里面它倒是给给wifi用。比电脑云端下载数据在打开方便了。

好的，我会综合考虑的，总体思路就是简洁，我不喜欢复杂的事物或操作，所以才有了Knot，😄

**Comment by xp12047** [comment]
> > 不能远程也没关系。有些好点的公司里面它倒是给给wifi用。比电脑云端下载数据在打开方便了。
> 
> 好的，我会综合考虑的，总体思路就是简洁，我不喜欢复杂的事物或操作，所以才有了Knot，😄

是这样的。所以我一开始建议你弄个cli客户端。它的安装包印象中一般都不大。简洁实用。

**Comment by ic005k** [comment]
> cli客户端

不论什么客户端，都需要先解决数据同步的问题，否则客户端就没存在的必要性了
数据互通是重点，客户端很好解决，非常简单的，分分钟的事

**Comment by xp12047** [comment]
> > cli客户端
> 
> 不论什么客户端，都需要先解决数据同步的问题，否则客户端就没存在的必要性了 数据互通是重点，客户端很好解决，非常简单的，分分钟的事

哦
