### ISSUE TITLE
笔记编辑完成的内容复制能不能给优化下

### ISSUE THREAD

**Issue by xp12047** [ic005k/Knot#9]
https://user-images.githubusercontent.com/56335408/206886534-efcb0703-e2c9-4a3e-b355-ae506e43e55f.mp4

对于编辑完成的内容有时我要复制。通常手机手滑选择在kont里面似乎不起作用。要想快点复制只有点击全选才会快些。抽空帮忙给优化下吧。

**Comment by ic005k** [comment]
目前的选择是通过按住 + 和 - 按钮，这个设计确实有点另类，初衷是为了解决某些手机边缘触控不灵敏的问题

好的，这个请完全放心，Knot还远远没有达到完善的地步，空闲的时候我会不断地改善和优化它，它将会越来越简洁和人性化
欢迎随时提出改进建议和使用心得

**Comment by xp12047** [comment]
> 目前的选择是通过按住 + 和 - 按钮，这个设计确实有点另类，初衷是为了解决某些手机边缘触控不灵敏的问题
> 
> 好的，这个请完全放心，Knot还远远没有达到完善的地步，空闲的时候我会不断地改善和优化它，它将会越来越简洁和人性化 欢迎随时提出改进建议和使用心得

好

**Comment by ic005k** [comment]
关于数据无缝同步的问题，已经有了解决方案，空闲的时候，我会推出一个版本，以支持各种同步工具或同步网盘。

我现在推荐的方案是这个，感兴趣的话，可以提前了解下：https://github.com/syncthing/syncthing

这样我工作中的待办和笔记都可以在各设备间无缝同步了，终于可以不用印象笔记之类的工具了

**Comment by xp12047** [comment]
> 关于数据无缝同步的问题，已经有了解决方案，空闲的时候，我会推出一个版本，以支持各种同步工具或同步网盘。
> 
> 我现在推荐的方案是这个，感兴趣的话，可以提前了解下：https://github.com/syncthing/syncthing
> 
> 这样我工作中的待办和笔记都可以在各设备间无缝同步了，终于可以不用印象笔记之类的工具了

这个开源项目我之前还加过星了看着用户是挺多的就是没好好看过😁。我没有往网盘上面去想。话说回来不知道这个是不是"编程随想"那个家伙用来备份的工具。

**Comment by ic005k** [comment]
嗯嗯，你先熟悉下它的配置和使用，Knot随后会进行适配，到时就可以利用它进行数据无缝同步了

**Comment by ic005k** [comment]
Knot适配后，会支持各种同步工具，包括各种同步盘等，也可支持你自己架设服务器等

**Comment by xp12047** [comment]
> 嗯嗯，你先熟悉下它的配置和使用，Knot随后会进行适配，到时就可以利用它进行数据无缝同步了

好的

**Comment by ic005k** [comment]
写了个小说明：https://github.com/ic005k/Knot/issues/10

一会发新版
